version: '3.4'

networks:
  ysc-net:
    external:
      name: ysc-net
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: reverse-proxy-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ysc-net
    ports:
      - '80:80'
    depends_on:
      - chessserver
      - middleware
      - stockfishserver
      - chessclient
      - ystemandchess
  chessserver:
    image: chessserver
    container_name: chessserver
    environment:
      - PORT=3000
    networks:
      - ysc-net
    expose:
      - '3000'
    volumes:
      - ../chessServer:/usr/src/app
  chessclient:
    image: chessclient
    container_name: chessclient
    environment:
      - PARENT=ystemandchess
    networks:
      - ysc-net
    expose:
      - '80'
    volumes:
      - ../chessClient:/usr/share/nginx/html
  stockfishserver:
    image: stockfishserver
    container_name: stockfishserver
    environment:
      - PORT=8080
    networks:
      - ysc-net
    expose:
      - '8080'
    volumes:
      - ../stockfishServer:/usr/src/app
  middleware:
    image: middleware
    container_name: middleware
    env_file:
      - ../middleware/environment.php
    networks:
      - ysc-net
    expose:
      - '8000'
    volumes:
      - ../middleware:/var/www/html
  ystemandchess:
    image: ystemandchess
    container_name: ystemandchess
    env_file:
      - ../YStemAndChess/src/environments/environment.ts
    networks:
      - ysc-net
    ports:
      - '80'
    depends_on:
      - middleware
      - stockfishserver
      - chessclient
      - chessserver
    volumes:
      - ../YStemAndChess:/usr/src/app/
      - /usr/src/app/node_modules
