import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root',
}) 
export class PuzzlesService {
    puzzleArray = [
        {
          "PuzzleId": "lliIw",
          "FEN": "r2qkb1r/pQ3ppp/2p2n2/3b4/2BP4/8/PP3PPP/RNB1K2R b KQkq - 0 11",
          "Moves": "d5c4 b7c6 f6d7 c6c4 a8c8 c4e2",
          "Rating": 1313,
          "RatingDeviation": 74,
          "Popularity": 95,
          "NbPlays": 11404,
          "Themes": "advantage fork long opening",
          "GameUrl": "https://lichess.org/06Fl2Wl7/black#22"
        },
        {
          "PuzzleId": "zDU1R",
          "FEN": "5rk1/2q1bppp/r1P1p3/pb1pP2P/3B4/RP3N2/2Q2PP1/R5K1 w - - 1 31",
          "Moves": "a3a5 a6a5 a1a5 c7a5",
          "Rating": 1051,
          "RatingDeviation": 84,
          "Popularity": 84,
          "NbPlays": 54,
          "Themes": "crushing middlegame short",
          "GameUrl": "https://lichess.org/b9o5RCFX#61"
        },
        {
          "PuzzleId": "Hvcp5",
          "FEN": "3r2k1/5p2/pp3p2/2b4b/5B1P/P4P2/1Pr5/K3R1R1 b - - 1 31",
          "Moves": "g8f8 f4h6",
          "Rating": 944,
          "RatingDeviation": 75,
          "Popularity": 100,
          "NbPlays": 268,
          "Themes": "mate mateIn1 middlegame oneMove",
          "GameUrl": "https://lichess.org/N0PSnsZY/black#62"
        },
        {
          "PuzzleId": "5JRb0",
          "FEN": "6r1/3kbp2/nqp1p3/1p1pPn2/r2P1Bpp/1NNP4/2Q2PPP/1RR3K1 b - - 3 30",
          "Moves": "f5d4 c3a4 d4c2 a4b6",
          "Rating": 1702,
          "RatingDeviation": 85,
          "Popularity": 29,
          "NbPlays": 38,
          "Themes": "crushing middlegame short",
          "GameUrl": "https://lichess.org/0hNBhyCu/black#60"
        },
        {
          "PuzzleId": "pxPqp",
          "FEN": "r2qr1k1/p1p2ppp/1bpp4/8/4P3/2N1B3/PP2QP2/R4RK1 w - - 2 17",
          "Moves": "e3b6 d8g5 g1h1 e8e6 f2f4 e6h6",
          "Rating": 2176,
          "RatingDeviation": 77,
          "Popularity": 89,
          "NbPlays": 100,
          "Themes": "crushing long middlegame",
          "GameUrl": "https://lichess.org/PDpIr0su#33"
        },
        {
          "PuzzleId": "SJkwc",
          "FEN": "5rk1/pp4p1/2p2r2/2b5/5BpP/P1N5/1P5K/R4R2 w - - 2 29",
          "Moves": "h2g2 f6f4 f1f4 f8f4",
          "Rating": 728,
          "RatingDeviation": 87,
          "Popularity": 64,
          "NbPlays": 177,
          "Themes": "advantage middlegame short",
          "GameUrl": "https://lichess.org/H2eIxMDs#57"
        },
        {
          "PuzzleId": "Vaxe1",
          "FEN": "2r3k1/ppq2pp1/7p/4R3/2Np4/PPnP3P/3Q1PP1/6K1 w - - 7 30",
          "Moves": "d2f4 c3e2 e5e2 c7f4",
          "Rating": 728,
          "RatingDeviation": 76,
          "Popularity": 100,
          "NbPlays": 452,
          "Themes": "crushing endgame kingsideAttack short",
          "GameUrl": "https://lichess.org/PArZrooz#59"
        },
        {
          "PuzzleId": "Oxsgx",
          "FEN": "r3k2r/ppp2ppp/2pbb3/8/7q/5BP1/PPP2P1P/R1BQR1K1 b kq - 0 12",
          "Moves": "h4h3 f3g4 h3g4 d1g4",
          "Rating": 1700,
          "RatingDeviation": 79,
          "Popularity": 92,
          "NbPlays": 118,
          "Themes": "crushing middlegame pin short",
          "GameUrl": "https://lichess.org/FFcMQvIU/black#24"
        },
        {
          "PuzzleId": "edyfO",
          "FEN": "3r1rk1/1p3ppp/p1np4/4q3/4P1b1/1N1B4/PPPQ2PP/1R3RK1 b - - 1 16",
          "Moves": "g4h5 f1f5 e5e7 f5h5",
          "Rating": 1321,
          "RatingDeviation": 73,
          "Popularity": 95,
          "NbPlays": 13156,
          "Themes": "advantage interference middlegame short",
          "GameUrl": "https://lichess.org/5ZwZ6nxb/black#32"
        },
        {
          "PuzzleId": "IVF6h",
          "FEN": "8/8/8/2kB1Rpp/2Pb4/8/r4PK1/8 b - - 1 44",
          "Moves": "c5d6 c4c5 d4c5 d5a2",
          "Rating": 1588,
          "RatingDeviation": 74,
          "Popularity": 92,
          "NbPlays": 3336,
          "Themes": "crushing discoveredAttack endgame short",
          "GameUrl": "https://lichess.org/Df2Ufy8x/black#88"
        }
      ];
  
  themesDescription = {
    "advancedPawn": "One of your pawns is deep into the opponent position, maybe threatening to promote.",
    "advantage": "Seize your chance to get a decisive advantage.",
    "anastasiaMate": "A knight and rook or queen team up to trap the opposing king between the side of the board and a friendly piece.",
    "arabianMate": "A knight and a rook team up to trap the opposing king on a corner of the board.",
    "attackingF2F7": "An attack focusing on the f2 or f7 pawn, such as in the fried liver opening.",
    "attraction": "An exchange or sacrifice encouraging or forcing an opponent piece to a square that allows a follow-up tactic.",
    "backRankMate": "Checkmate the king on the home rank, when it is trapped there by its own pieces.",
    "bishopEndgame": "An endgame with only bishops and pawns.",
    "bodenMate": "Two attacking bishops on criss-crossing diagonals deliver mate to a king obstructed by friendly pieces.",
    "castling": "Bring the king to safety, and deploy the rook for attack.",
    "capturingDefender": "Removing a piece that is critical to defence of another piece, allowing the now undefended piece to be captured on a following move.",
    "crushing": "Spot the opponent blunder to obtain a crushing advantage.",
    "doubleBishopMate": "Two attacking bishops on adjacent diagonals deliver mate to a king obstructed by friendly pieces.",
    "dovetailMate": "A queen delivers mate to an adjacent king, whose only two escape squares are obstructed by friendly pieces.",
    "equality": "Come back from a losing position, and secure a draw or a balanced position.",
    "kingsideAttack": "An attack of the opponent's king, after they castled on the king side.",
    "clearance": "A move, often with tempo, that clears a square, file or diagonal for a follow-up tactical idea.",
    "defensiveMove": "A precise move or sequence of moves that is needed to avoid losing material or another advantage.",
    "deflection": "A move that distracts an opponent piece from another duty that it performs, such as guarding a key square. Sometimes also called \"overloading\".",
    "discoveredAttack": "Moving a piece (such as a knight), that previously blocked an attack by a long range piece (such as a rook), out of the way of that piece.",
    "doubleCheck": "Checking with two pieces at once, as a result of a discovered attack where both the moving piece and the unveiled piece attack the opponent's king.",
    "endgame": "A tactic during the last phase of the game.",
    "enPassant": "A tactic involving the en passant rule, where a pawn can capture an opponent pawn that has bypassed it using its initial two-square move.",
    "exposedKing": "A tactic involving a king with few defenders around it, often leading to checkmate.",
    "fork": "A move where the moved piece attacks two opponent pieces at once.",
    "hangingPiece": "A tactic involving an opponent piece being undefended or insufficiently defended and free to capture.",
    "hookMate": "Checkmate with a rook, knight, and pawn along with one enemy pawn to limit the enemy king's escape.",
    "interference": "Moving a piece between two opponent pieces to leave one or both opponent pieces undefended, such as a knight on a defended square between two rooks.",
    "intermezzo": "Instead of playing the expected move, first interpose another move posing an immediate threat that the opponent must answer. Also known as \"Zwischenzug\" or \"In between\".",
    "knightEndgame": "An endgame with only knights and pawns.",
    "long": "Three moves to win.",
    "master": "Puzzles from games played by titled players.",
    "masterVsMaster": "Puzzles from games between two titled players.",
    "mate": "Win the game with style.",
    "mateIn1": "Deliver checkmate in one move.",
    "mateIn2": "Deliver checkmate in two moves.",
    "mateIn3": "Deliver checkmate in three moves.",
    "mateIn4": "Deliver checkmate in four moves.",
    "mateIn5": "Figure out a long mating sequence.",
    "middlegame": "A tactic during the second phase of the game.",
    "oneMove": "A puzzle that is only one move long.",
    "opening": "A tactic during the first phase of the game.",
    "pawnEndgame": "An endgame with only pawns.",
    "pin": "A tactic involving pins, where a piece is unable to move without revealing an attack on a higher value piece.",
    "promotion": "Promote one of your pawn to a queen or minor piece.",
    "queenEndgame": "An endgame with only queens and pawns.",
    "queenRookEndgame": "An endgame with only queens, rooks and pawns.",
    "queensideAttack": "An attack of the opponent's king, after they castled on the queen side.",
    "quietMove": "A move that does neither make a check or capture, nor an immediate threat to capture, but does prepare a more hidden unavoidable threat for a later move.",
    "rookEndgame": "An endgame with only rooks and pawns.",
    "sacrifice": "A tactic involving giving up material in the short-term, to gain an advantage again after a forced sequence of moves.",
    "short": "Two moves to win.",
    "skewer": "A motif involving a high value piece being attacked, moving out the way, and allowing a lower value piece behind it to be captured or attacked, the inverse of a pin.",
    "smotheredMate": "A checkmate delivered by a knight in which the mated king is unable to move because it is surrounded (or smothered) by its own pieces.",
    "superGM": "Puzzles from games played by the best players in the world.",
    "trappedPiece": "A piece is unable to escape capture as it has limited moves.",
    "underPromotion": "Promotion to a knight, bishop, or rook.",
    "veryLong": "Four moves or more to win.",
    "xRayAttack": "A piece attacks or defends a square, through an enemy piece.",
    "zugzwang": "The opponent is limited in the moves they can make, and all moves worsen their position.",
    "healthyMix": "A bit of everything. You don't know what to expect, so you remain ready for anything! Just like in real games.",
    "playerGames": "Lookup puzzles generated from your games, or from another player's games."
  };

  themesName = {
    "advancedPawn": "Advanced pawn",
    "advantage": "Advantage",
    "anastasiaMate": "Anastasia's mate",
    "arabianMate": "Arabian mate",
    "attackingF2F7": "Attacking f2 or f7",
    "attraction": "Attraction",
    "backRankMate": "Back rank mate",
    "bishopEndgame": "Bishop endgame",
    "bodenMate": "Boden's mate",
    "castling": "Castling",
    "capturingDefender": "Capture the defender",
    "crushing": "Crushing",
    "doubleBishopMate": "Double bishop mate",
    "dovetailMate": "Dovetail mate",
    "equality": "Equality",
    "kingsideAttack": "Kingside attack",
    "clearance": "Clearance",
    "defensiveMove": "Defensive move",
    "deflection": "Deflection",
    "discoveredAttack": "Discovered attack",
    "doubleCheck": "Double check",
    "endgame": "Endgame",
    "enPassant": "En passant",
    "exposedKing": "Exposed king",
    "fork": "Fork",
    "hangingPiece": "Hanging piece",
    "hookMate": "Hook mate",
    "interference": "Interference",
    "intermezzo": "Intermezzo",
    "knightEndgame": "Knight endgame",
    "long": "Long puzzle",
    "master": "Master games",
    "masterVsMaster": "Master vs Master games",
    "mate": "Checkmate",
    "mateIn1": "Mate in 1",
    "mateIn2": "Mate in 2",
    "mateIn3": "Mate in 3",
    "mateIn4": "Mate in 4",
    "mateIn5": "Mate in 5 or more",
    "middlegame": "Middlegame",
    "oneMove": "One-move puzzle",
    "opening": "Opening",
    "pawnEndgame": "Pawn endgame",
    "pin": "Pin",
    "promotion": "Promotion",
    "queenEndgame": "Queen endgame",
    "queenRookEndgame": "Queen and Rook",
    "queensideAttack": "Queenside attack",
    "quietMove": "Quiet move",
    "rookEndgame": "Rook endgame",
    "sacrifice": "Sacrifice",
    "short": "Short puzzle",
    "skewer": "Skewer",
    "smotheredMate": "Smothered mate",
    "superGM": "Super GM games",
    "trappedPiece": "Trapped piece",
    "underPromotion": "Underpromotion",
    "veryLong": "Very long puzzle",
    "xRayAttack": "X-Ray attack",
    "zugzwang": "Zugzwang",
    "healthyMix": "Healthy mix",
    "playerGames": "Player games"
  };
}